from __future__ import annotations

import argparse
from dataclasses import asdict
from datetime import datetime, timezone
import json
import math
import os
from pathlib import Path
from typing import Any, Sequence
import uuid

import numpy as np

from .OgameData import UNIT_SPECS
from .OgameUtils import CombatConfig, TechLevels, generate_random_defense
from .optimizer import (
    AttackProblem,
    DefenseFitnessConfig,
    EvolutionConfig,
    EvolutionaryOptimizer,
    HybridAnalysisPopulationInitializer,
    HybridInitializerConfig,
    ReliableDefenseFitnessEvaluator,
    decode_attack_genome,
    make_combat_seeds,
)


DEFAULT_COUNT = 100
DEFAULT_MIN_POINTS = 200.0
DEFAULT_MAX_POINTS = 200_000.0
DEFAULT_POPULATION_SIZE = 64
DEFAULT_GENERATIONS = 50
DEFAULT_TRAINING_SIMULATIONS = 12
DEFAULT_SEARCH_WIN_RATE = 0.90
DEFAULT_VALIDATION_SIMULATIONS = 128
DEFAULT_VALIDATION_WIN_RATE = 0.95
DEFAULT_VALIDATION_CANDIDATES = 20
DEFAULT_RESTARTS = 2
DEFAULT_PROGRESS_EVERY = 1
DEFAULT_MIN_MULTIPLIER = 0.50
DEFAULT_MAX_MULTIPLIER = 6.00
DEFAULT_ANALYSIS = Path("data/OGIA/Analisis/merged_battles_1_analysis.json")
FIXED_TECH_LEVEL = 15


def _positive_int(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def _non_negative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be a non-negative integer")
    return parsed


def _positive_float(value: str) -> float:
    parsed = float(value)
    if not math.isfinite(parsed) or parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive finite number")
    return parsed


def _probability(value: str) -> float:
    parsed = float(value)
    if not math.isfinite(parsed) or not 0 < parsed <= 1:
        raise argparse.ArgumentTypeError("must be in (0, 1]")
    return parsed


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ogia-generate-perfect-pairs",
        description=(
            "Generate defense/optimized-attack pairs with the OGIA evolutionary "
            "optimizer and save accepted pairs incrementally as JSONL."
        ),
    )
    parser.add_argument("--count", type=_positive_int, default=DEFAULT_COUNT)
    parser.add_argument("--min-points", type=_positive_float, default=DEFAULT_MIN_POINTS)
    parser.add_argument("--max-points", type=_positive_float, default=DEFAULT_MAX_POINTS)
    parser.add_argument("--population-size", type=_positive_int, default=DEFAULT_POPULATION_SIZE)
    parser.add_argument("--generations", type=_non_negative_int, default=DEFAULT_GENERATIONS)
    parser.add_argument(
        "--training-simulations",
        type=_positive_int,
        default=DEFAULT_TRAINING_SIMULATIONS,
        help="Common combat seeds used to score every genome during evolution.",
    )
    parser.add_argument(
        "--search-win-rate",
        type=_probability,
        default=DEFAULT_SEARCH_WIN_RATE,
        help="Reliability threshold used inside evolutionary fitness.",
    )
    parser.add_argument(
        "--validation-simulations",
        type=_positive_int,
        default=DEFAULT_VALIDATION_SIMULATIONS,
        help="Independent combat seeds used to validate final candidates.",
    )
    parser.add_argument(
        "--validation-win-rate",
        type=_probability,
        default=DEFAULT_VALIDATION_WIN_RATE,
        help="Minimum independent win rate required before a pair is saved.",
    )
    parser.add_argument(
        "--validation-candidates",
        type=_positive_int,
        default=DEFAULT_VALIDATION_CANDIDATES,
        help="Number of diverse final candidates re-tested on validation seeds.",
    )
    parser.add_argument("--restarts", type=_positive_int, default=DEFAULT_RESTARTS)
    parser.add_argument(
        "--min-multiplier",
        type=_positive_float,
        default=DEFAULT_MIN_MULTIPLIER,
    )
    parser.add_argument(
        "--max-multiplier",
        type=_positive_float,
        default=DEFAULT_MAX_MULTIPLIER,
    )
    parser.add_argument(
        "--analysis",
        type=Path,
        default=DEFAULT_ANALYSIS,
        help=f"Optimizer-prior JSON generated by ogia-analyze-battles (default: {DEFAULT_ANALYSIS}).",
    )
    parser.add_argument("--progress-every", type=_positive_int, default=DEFAULT_PROGRESS_EVERY)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="JSONL output path. Defaults to data/OGIA/perfect_pairs/<timestamp>.jsonl.",
    )
    return parser


def _sample_log_uniform(
    rng: np.random.Generator,
    minimum: float,
    maximum: float,
) -> float:
    if minimum == maximum:
        return float(minimum)
    return float(math.exp(rng.uniform(math.log(minimum), math.log(maximum))))


def _default_output_path() -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    return Path("data") / "OGIA" / "perfect_pairs" / f"perfect_pairs_{timestamp}.jsonl"


def _generation_history(history) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for stats in history:
        rows.append(
            {
                "generation": int(stats.generation),
                "best_score": float(stats.best_score),
                "mean_score": float(stats.mean_score),
                "worst_score": float(stats.worst_score),
                "best_genome": {
                    "ship_weights": dict(stats.best_genome.normalized_weights()),
                    "points_multiplier": float(stats.best_genome.points_multiplier),
                },
            }
        )
    return rows


def _candidate_fleet_key(record: dict[str, Any]) -> tuple[tuple[str, int], ...]:
    metrics = record["individual"].evaluation.metrics
    fleet = metrics.get("fleet", {})
    return tuple(sorted((str(name), int(count)) for name, count in fleet.items()))


def _select_validation_candidates(
    candidate_records: Sequence[dict[str, Any]],
    *,
    limit: int,
    reliable_win_rate: float,
) -> list[dict[str, Any]]:
    if not candidate_records:
        return []

    by_score = sorted(
        candidate_records,
        key=lambda record: record["individual"].evaluation.score,
        reverse=True,
    )
    by_win_rate = sorted(
        candidate_records,
        key=lambda record: float(
            record["individual"].evaluation.metrics.get("win_rate", 0.0)
        ),
        reverse=True,
    )
    reliable = [
        record
        for record in candidate_records
        if float(record["individual"].evaluation.metrics.get("win_rate", 0.0))
        >= reliable_win_rate
    ]
    by_small_reliable = sorted(
        reliable,
        key=lambda record: (
            float(record["individual"].evaluation.metrics.get("actual_multiplier", float("inf"))),
            float(record["individual"].evaluation.metrics.get("mean_loss_ratio", float("inf"))),
        ),
    )

    score_quota = max(1, limit // 2)
    win_quota = max(1, limit // 4)
    small_quota = max(1, limit - score_quota - win_quota)

    selected: list[dict[str, Any]] = []
    seen: set[tuple[tuple[str, int], ...]] = set()

    def add(records: Sequence[dict[str, Any]], quota: int) -> None:
        added = 0
        for record in records:
            key = _candidate_fleet_key(record)
            if key in seen:
                continue
            seen.add(key)
            selected.append(record)
            added += 1
            if len(selected) >= limit or added >= quota:
                break

    add(by_score, score_quota)
    if len(selected) < limit:
        add(by_win_rate, win_quota)
    if len(selected) < limit:
        add(by_small_reliable, small_quota)
    if len(selected) < limit:
        add(by_score, limit - len(selected))

    return selected[:limit]


def _attacker_composition_details(decoded, genome, allowed_ships) -> dict[str, Any]:
    point_values: dict[str, float] = {}
    for ship_name, count in decoded.fleet.items():
        spec = UNIT_SPECS[ship_name]
        point_values[ship_name] = float(spec.cost) / 1_000.0 * int(count)

    total_points = sum(point_values.values())
    actual_percentages = {
        ship_name: (100.0 * value / total_points if total_points > 0 else 0.0)
        for ship_name, value in point_values.items()
    }

    return {
        "fleet": dict(decoded.fleet),
        "target_points": float(decoded.target_attacker_points),
        "actual_points": float(decoded.actual_attacker_points),
        "point_difference": float(decoded.actual_attacker_points - decoded.target_attacker_points),
        "requested_multiplier": float(genome.points_multiplier),
        "actual_multiplier": float(decoded.actual_attacker_points / decoded.defender_points),
        "requested_percentages": genome.percentages(allowed_ships),
        "actual_percentages": actual_percentages,
    }


def _generate_one_pair(
    rng: np.random.Generator,
    *,
    run_seed: int | None,
    sequence_index: int,
    attempt_index: int,
    min_points: float,
    max_points: float,
    initializer: HybridAnalysisPopulationInitializer,
    initializer_config: HybridInitializerConfig,
    evolution_config: EvolutionConfig,
    fitness_config: DefenseFitnessConfig,
    validation_simulations: int,
    validation_win_rate: float,
    validation_candidates: int,
    restarts: int,
    analysis_path: Path,
) -> dict[str, Any] | None:
    defender_target_points = _sample_log_uniform(rng, min_points, max_points)
    defense_details = generate_random_defense(
        target_points=defender_target_points,
        min_unit_types=2,
        max_unit_types=6,
        include_shield_domes=True,
        rng=rng,
        return_details=True,
    )
    defender = defense_details["defense"]

    fixed_tech = TechLevels(
        weapons=FIXED_TECH_LEVEL,
        shielding=FIXED_TECH_LEVEL,
        armour=FIXED_TECH_LEVEL,
    )
    combat_config = CombatConfig()
    problem = AttackProblem(
        defender=defender,
        attacker_tech=fixed_tech,
        defender_tech=fixed_tech,
        combat_config=combat_config,
    )

    candidate_records: list[dict[str, Any]] = []
    restart_summaries: list[dict[str, Any]] = []

    for restart_index in range(restarts):
        optimizer_seed = int(rng.integers(0, 2**32 - 1))
        combat_seed = int(rng.integers(0, 2**32 - 1))
        evaluator = ReliableDefenseFitnessEvaluator(
            evolution_config=evolution_config,
            fitness_config=fitness_config,
            combat_seed=combat_seed,
        )

        report_every = max(1, evolution_config.generations // 5) if evolution_config.generations else 1

        def on_generation(stats, *, _restart=restart_index):
            if (
                stats.generation == 0
                or stats.generation == evolution_config.generations
                or stats.generation % report_every == 0
            ):
                print(
                    f"[pair {sequence_index} attempt {attempt_index} restart {_restart + 1}/{restarts}] "
                    f"generation {stats.generation}/{evolution_config.generations} "
                    f"best={stats.best_score:.5f}",
                    flush=True,
                )

        optimizer = EvolutionaryOptimizer(
            config=evolution_config,
            initializer=initializer,
            fitness_evaluator=evaluator,
            on_generation=on_generation,
        )
        result = optimizer.optimize(problem, seed=optimizer_seed)

        restart_summaries.append(
            {
                "restart_index": int(restart_index),
                "optimizer_seed": int(optimizer_seed),
                "combat_seed": int(combat_seed),
                "training_simulations_per_genome": int(fitness_config.simulations_per_genome),
                "best_score": float(result.best.evaluation.score),
                "best_metrics": dict(result.best.evaluation.metrics),
            }
        )

        for individual in result.final_population:
            candidate_records.append(
                {
                    "individual": individual,
                    "restart_index": restart_index,
                    "history": result.history,
                }
            )

    candidates = _select_validation_candidates(
        candidate_records,
        limit=validation_candidates,
        reliable_win_rate=fitness_config.reliable_win_rate,
    )
    if not candidates:
        return None

    validation_seed = int(rng.integers(0, 2**32 - 1))
    validation_seeds = make_combat_seeds(
        validation_simulations,
        seed=validation_seed,
    )
    validation_evaluator = ReliableDefenseFitnessEvaluator(
        evolution_config=evolution_config,
        fitness_config=fitness_config,
        combat_seed=validation_seed,
    )

    validated: list[tuple[dict[str, Any], Any]] = []
    validation_summaries: list[dict[str, Any]] = []
    for candidate_index, record in enumerate(candidates):
        individual = record["individual"]
        evaluation = validation_evaluator.evaluate_genome(
            problem,
            individual.genome,
            combat_seeds=validation_seeds,
            use_cache=False,
        )
        metrics = dict(evaluation.metrics)
        passed = float(metrics["win_rate"]) >= validation_win_rate
        validation_summaries.append(
            {
                "candidate_index": int(candidate_index),
                "restart_index": int(record["restart_index"]),
                "passed": bool(passed),
                "metrics": metrics,
            }
        )
        if passed:
            validated.append((record, evaluation))

    if not validated:
        return None

    selected_record, validation = min(
        validated,
        key=lambda item: (
            float(item[1].metrics["actual_multiplier"]),
            float(item[1].metrics["mean_loss_ratio"]),
            -float(item[1].metrics["win_rate"]),
        ),
    )
    selected = selected_record["individual"]
    decoded = decode_attack_genome(
        selected.genome,
        defender,
        allowed_ships=evolution_config.allowed_ships,
    )
    attacker_details = _attacker_composition_details(
        decoded,
        selected.genome,
        evolution_config.allowed_ships,
    )

    normalized_weights = selected.genome.normalized_weights(evolution_config.allowed_ships)
    target = {
        "attacker": dict(decoded.fleet),
        "ship_weights": normalized_weights,
        "ship_percentages": selected.genome.percentages(evolution_config.allowed_ships),
        "points_multiplier": float(selected.genome.points_multiplier),
        "actual_points_multiplier": float(validation.metrics["actual_multiplier"]),
    }

    return {
        "schema_version": 1,
        "pair_id": uuid.uuid4().hex,
        "sequence_index": int(sequence_index),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "generation": {
            "run_seed": run_seed,
            "attempt_index": int(attempt_index),
            "defender_target_points": float(defender_target_points),
            "analysis_path": str(analysis_path),
            "fixed_technology_level": FIXED_TECH_LEVEL,
            "validation_seed": int(validation_seed),
        },
        "inputs": {
            "defender": dict(defender),
            "attacker_tech": asdict(fixed_tech),
            "defender_tech": asdict(fixed_tech),
            "combat_config": asdict(combat_config),
        },
        "target": target,
        "composition_details": {
            "attacker": attacker_details,
            "defender": defense_details,
        },
        "optimizer": {
            "evolution_config": asdict(evolution_config),
            "initializer_config": asdict(initializer_config),
            "fitness_config": asdict(fitness_config),
            "restarts": restart_summaries,
            "selected_restart_index": int(selected_record["restart_index"]),
            "selected_training_score": float(selected.evaluation.score),
            "selected_training_metrics": dict(selected.evaluation.metrics),
            "selected_history": _generation_history(selected_record["history"]),
        },
        "validation": {
            "required_win_rate": float(validation_win_rate),
            "simulations": int(validation_simulations),
            "passed": True,
            "selected_metrics": dict(validation.metrics),
            "candidates_tested": int(len(candidates)),
            "candidate_summaries": validation_summaries,
        },
    }


def run(args: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    options = parser.parse_args(list(args or []))

    min_points = float(options.min_points)
    max_points = float(options.max_points)
    if max_points < min_points:
        parser.error("--max-points must be greater than or equal to --min-points")
    if options.population_size < 4:
        parser.error("--population-size must be at least 4")
    if options.max_multiplier < options.min_multiplier:
        parser.error("--max-multiplier must be >= --min-multiplier")
    if options.validation_win_rate < options.search_win_rate:
        parser.error("--validation-win-rate must be >= --search-win-rate")

    analysis_path = options.analysis.expanduser()
    if not analysis_path.is_file():
        parser.error(
            f"Analysis JSON not found: {analysis_path}. Run ogia-analyze-battles first."
        )

    output_path = (options.output or _default_output_path()).expanduser()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    initializer_config = HybridInitializerConfig()
    initializer = HybridAnalysisPopulationInitializer.from_json(
        analysis_path,
        initializer_config=initializer_config,
    )

    elite_count = max(1, min(8, options.population_size // 16 or 1))
    tournament_size = min(4, options.population_size)
    evolution_config = EvolutionConfig(
        population_size=int(options.population_size),
        generations=int(options.generations),
        elite_count=int(elite_count),
        tournament_size=int(tournament_size),
        min_points_multiplier=float(options.min_multiplier),
        max_points_multiplier=float(options.max_multiplier),
    )
    fitness_config = DefenseFitnessConfig(
        simulations_per_genome=int(options.training_simulations),
        reliable_win_rate=float(options.search_win_rate),
    )

    rng = np.random.default_rng(options.seed)
    saved = 0
    failed = 0
    attempts = 0
    max_attempts = max(options.count * 5, options.count + 20)

    print("OGIA perfect-pair generator")
    print(f"Target accepted pairs: {options.count:,}")
    print(f"Defense point range: {min_points:g} - {max_points:g}")
    print(f"Population: {evolution_config.population_size}")
    print(f"Generations: {evolution_config.generations}")
    print(f"Training simulations/genome: {fitness_config.simulations_per_genome}")
    print(f"Search reliability threshold: {fitness_config.reliable_win_rate:.1%}")
    print(f"Validation: {options.validation_simulations} battles at {options.validation_win_rate:.1%}")
    print(f"Optimizer restarts/defense: {options.restarts}")
    print(f"Technology levels: {FIXED_TECH_LEVEL}/{FIXED_TECH_LEVEL}/{FIXED_TECH_LEVEL} both sides")
    print(f"Analysis priors: {analysis_path}")
    print(f"Output: {output_path}")
    print(f"Seed: {options.seed if options.seed is not None else 'random'}")

    try:
        with output_path.open("a", encoding="utf-8") as output_file:
            while saved < options.count:
                attempts += 1
                if attempts > max_attempts:
                    raise RuntimeError(
                        "Too many optimizer attempts without enough validated pairs: "
                        f"{saved} saved, {failed} failed."
                    )

                try:
                    record = _generate_one_pair(
                        rng,
                        run_seed=options.seed,
                        sequence_index=saved + 1,
                        attempt_index=attempts,
                        min_points=min_points,
                        max_points=max_points,
                        initializer=initializer,
                        initializer_config=initializer_config,
                        evolution_config=evolution_config,
                        fitness_config=fitness_config,
                        validation_simulations=int(options.validation_simulations),
                        validation_win_rate=float(options.validation_win_rate),
                        validation_candidates=int(options.validation_candidates),
                        restarts=int(options.restarts),
                        analysis_path=analysis_path,
                    )
                except Exception as exc:
                    failed += 1
                    print(
                        f"[warning] optimizer attempt {attempts} failed with "
                        f"{type(exc).__name__}: {exc}",
                        flush=True,
                    )
                    continue

                if record is None:
                    failed += 1
                    print(
                        f"[warning] attempt {attempts}: no candidate reached "
                        f"{options.validation_win_rate:.1%} validation win rate.",
                        flush=True,
                    )
                    continue

                output_file.write(
                    json.dumps(record, ensure_ascii=False, separators=(",", ":"))
                    + "\n"
                )
                output_file.flush()
                saved += 1

                if (
                    saved == 1
                    or saved % options.progress_every == 0
                    or saved == options.count
                ):
                    os.fsync(output_file.fileno())
                    validation_metrics = record["validation"]["selected_metrics"]
                    print(
                        f"Saved {saved:,}/{options.count:,} · "
                        f"validation win rate={validation_metrics['win_rate']:.1%} · "
                        f"multiplier={validation_metrics['actual_multiplier']:.3f}x · "
                        f"failed defenses={failed:,}",
                        flush=True,
                    )
    except KeyboardInterrupt:
        print(
            f"\nStopped by user. {saved:,} validated pairs were saved to {output_path}.",
            flush=True,
        )
        return 130

    print(
        f"Completed. {saved:,} validated pairs saved to {output_path}. "
        f"Failed optimizer attempts: {failed:,}.",
        flush=True,
    )
    return 0
